//
//  CalendarManager.swift
//  TUHub
//
//  Created by Noah Scardina on 12/5/25.
//

import EventKit

/**
 This class was generated by ChatGPT. I asked it the following prompt:
 "I want to create a new event in a user's calendar with EventKit in my SwiftUI app. How can I do this where I set the data in the event with values from in my code?"
 
 The code was revised based on the what it said in the following prompt:
 "I am getting the error "XPC connection was invalidated". How can I fix this?"
 
 I also added the NSCalendarsUsageDescription key to the xcodeproj file based on ChatGPT's
 answer to this prompt:
 "Do I need to add any permissions to my .xcodeproj file in order for this code to work?"
 
 I had previously looked at some Apple Developer articles about this:
 https://developer.apple.com/documentation/eventkit/creating-events-and-reminders
 https://developer.apple.com/documentation/eventkit/accessing-the-event-store
 https://developer.apple.com/documentation/eventkit/ekeventstore/save(_:span:commit:)
 */
@MainActor
final class CalendarManager: ObservableObject {
    private let store = EKEventStore()
    @Published var hasAccess = false

    func requestAccessIfNeeded() async throws {
        let status = EKEventStore.authorizationStatus(for: .event)

        if status == .notDetermined {
            hasAccess = try await store.requestFullAccessToEvents()
        } else {
            hasAccess = (status == .authorized)
        }
    }

    func addEvent(title: String, whenEventIs: Date) throws {
        guard hasAccess else {
            throw NSError(domain: "Calendar", code: 1, userInfo: [
                NSLocalizedDescriptionKey: "No access to Calendar"
            ])
        }

        let event = EKEvent(eventStore: store)
        event.title = title
        event.startDate = whenEventIs
        event.endDate = whenEventIs
        event.isAllDay = true
        event.calendar = store.defaultCalendarForNewEvents

        try store.save(event, span: .thisEvent)
    }
}

